<a href="https://colab.research.google.com/github/sreelakshmisajeevan-854/Hospital-Patient-Data-Analysis/blob/main/Hospital-Patient-Data-Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

1.	Load the patient dataset and show summary with info().

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Datasets/Patient_Data.csv')
df1=df.copy()
df1

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [ ]:
df1[['PatientID','Department','Doctor','BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [ ]:
df1 = df1.drop(['ReceptionistID','CheckInTime'],axis=1)

In [ ]:
df1

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [ ]:

department_bill_amount = df1.groupby('Department')['BillAmount'].sum().reset_index()

display(department_bill_amount)

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

5.	Remove duplicate patient records based on PatientID.

In [ ]:
df1_new=df1.drop_duplicates().copy()
df1_new

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

6.	Fill missing BillAmount values with the mean bill amount.

In [ ]:
df1_new['BillAmount']=df1_new['BillAmount'].fillna(df1_new['BillAmount'].mean())
df1_new

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

7.	Merge the billing dataset with patient dataset on PatientID.

In [ ]:
df2=pd.read_csv('/content/drive/MyDrive/Datasets/Billing_Data.csv')

In [ ]:
merged_df = pd.merge(df1_new, df2, on='PatientID', how='inner')
display(merged_df)

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [ ]:
new_patients_data = {
    'PatientID': [106, 107],
    'Name': ['Licy', 'George'],
    'Department': ['Pediatrics', 'Neurology'],
    'Doctor': ['Dr. Ann', 'Dr. Alan'],
    'BillAmount': [4500.00, 8000.00],

}
new_patients_df = pd.DataFrame(new_patients_data)
display(new_patients_df)

   PatientID    Name  Department    Doctor  BillAmount
0        106    Licy  Pediatrics   Dr. Ann      4500.0
1        107  George   Neurology  Dr. Alan      8000.0

In [ ]:
combined_df = pd.concat([df1_new, new_patients_df], ignore_index=True)
display(combined_df)

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106     Licy   Pediatrics    Dr. Ann  4500.000000
6        107   George    Neurology   Dr. Alan  8000.000000

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [ ]:
Final_df = pd.merge(combined_df, df2[['PatientID', 'InsuranceCovered', 'FinalAmount']], on='PatientID', how='left')
display(combined_df)

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0
5,106,Licy,Pediatrics,Dr. Ann,4500.000000,NaN,NaN
6,107,George,Neurology,Dr. Alan,8000.000000,NaN,NaN